### ISSUE TITLE
Unexpected album results using Discogs

### ISSUE THREAD

**Issue by vlur** [elamperti/OpenWebScrobbler#176]
The search function no longer returns relevant results. I've been using Discogs rather than Last.fm API for a long time on the advice from #167.

Searching for an artist name now returns tons of garbage results (in this case, I suspect it's finding Beato's name in the album credits, since he worked as a producer on at least two of the albums pictured, but he is not the main artist):

![Screenshot_2022-04-05_21-45-59](https://user-images.githubusercontent.com/44228316/161885770-25458ec4-791f-4451-a8e5-0c335c217b58.png)

Clicking on the artist name on the right takes me to a completely different artist page:

![Screenshot_2022-04-05_21-46-24](https://user-images.githubusercontent.com/44228316/161885811-18b03118-fd53-4bd5-8794-287fc97f1921.png)

I tried switching back to the Last.fm API but the ever-annoying "this album appears to be empty" bug still exists.

**Comment by elamperti** [comment]
Thanks for taking the time to open an issue and share your concern! I'll look into this issue. I'm afraid it may just be what Discogs is returning, but in any case it's worth a look. Hopefully it's just a mistake on my part and it's something that can be fixed quickly.

**Comment by elamperti** [comment]
A quick look at this suggests it's a problem with Discogs, as it shows the exact same result both searching for "Rick Beato" ([link](https://www.discogs.com/search/?q=rick+beato&type=all)) and in [the artist page](https://www.discogs.com/artist/739088-Rick-Beato). Does this happen with any other artist/album for you?

**Comment by vlur** [comment]
Thank you for making this tool - it's been handy for me in the past.

Yes, I've noticed the same behavior with other searches in the last couple weeks. Another example: "Weedian" is a stoner rock/metal compilation disc artist, so the _album artist_ would be "Weedian" and then each song would be "Artist - Title" if that makes sense.

But, doing a search for Weedian on OpenScrobbler returns a handful of results for "Sleep" and "Hookers*". Clicking on the artist name "Weedian" on the right brings me to "Search / "weedian" / Various" where the sole result is "Blue Grass Doom Comp. Vol 1" by Various. Contrast this with the same search on Discogs: [link](https://www.discogs.com/search/?q=weedian&type=all) and [the artist page on Discogs](https://www.discogs.com/label/1875037-Weedian).

Another thing I noticed changing recently, which may or may not be related: the album covers returned in an OpenScrobbler search now look much more low-res, jaggy, washed-out colors and so forth. Maybe the result of pulling tiny thumbnails instead of main images?

I'm not sure what, but it does seem like Discogs probably changed something about how their system works recently.

**Comment by elamperti** [comment]
Thanks for your helpful comment! In the case of Weedian, the related artist page is [this one](https://www.discogs.com/artist/1196442-Weedian), the one you linked is a label. There's another artist called ["The Weedian"](https://www.discogs.com/artist/1255076-The-Weedian) which has the results you mentioned (the ones by "Hookers"). Considering this is a compilation album, there's no real _artist_ for it (hence the _Various_ used in Discogs), so the only reliable way of finding it is searching for the album title (e.g. "Trip to England").

In this particular case, the compilation is a _release_, which the scrobbler is explicitly asking Discogs to filter as this causes a lot of duplicates for mainstream albums (i.e. you'd get several instances of the same album which differ in very small details such as the country where it was released, artwork or other data that doesn't make a difference when you scrobble -because last.fm doesn't care about that extra data-). As it is now, there's no way of finding it in the search directly! But it can be crafted from the Discogs release ID, which is not practical (but as an example, here's [Trip to England](https://openscrobbler.com/scrobble/album/view/dsid/release-20717965)).

Image sizes probably changed, or something in the scrobbler layout changed, and I agree they look bad as they are. There's a bigger cover image resource available so I'll check if it's possible to replace them or add both as a srcset to save bandwidth in mobile devices.

I also noticed artists' images aren't being displayed so that's something more to look into.

---

Current action items:

  * [ ] Add a checkbox to include releases in Discogs' search results, to account for this and other edge cases
  * [ ] Use a srcset for cover images or replace them with higher quality resource
  * [ ] Check why artist images are not displaying and fix it

**Comment by vlur** [comment]
Ah, makes sense @ "releases," especially the example. I had a couple of those, too (where the album does not show up in OS search results but the page does exist). In my case, I managed to find one of the Weedian albums by searching for a song title or artist name present on the compilation (i.e. something besides "Weedian" or "Trip to _____"). But I think that was just good luck and persistence on my part.

The checkbox etc. all sound like good additions :) Thanks again for OS and for looking into this.

**Comment by elamperti** [comment]
I've already implemented the changes mentioned above and they will be present in the next update (>=2.6.7). I hope this yields better results for everyone! 🙂
