### ISSUE TITLE
Add option to pin Swap artist and track option

### ISSUE THREAD

**Issue by nighto** [elamperti/OpenWebScrobbler#246]
**Is your feature request related to a problem? Please describe**
Some mixtapes have tracklists listed with "Track - Artist" instead of "Artist - Track" order ([example](https://www.youtube.com/watch?v=Nh9BrD3xIeU&ab_channel=MostlyHairless)). You can copy paste each entry manually but you must click on the swap button everytime.

**Describe the solution you'd like**
I think it would be nice to have a pin option next to the swap button so that when you paste data that can be splitted into Artist and Track, it would automatically already swap it.

**Comment by elamperti** [comment]
Hi @nighto! You can actually paste the text into the «track» input (instead of pasting into «artist») and it will split it backwards 😁 

For example, pasting this:
![image](https://github.com/user-attachments/assets/3a704aa4-d4bc-4e9b-a9d8-f5c2dc20d8ff)

Results in this:
![image](https://github.com/user-attachments/assets/ea598f7a-2813-48cc-a655-9d812ff52093)

Hope this helps! (if not, feel free to reopen the issue)

**Comment by nighto** [comment]
Oh, nice! TIL :)
