### ISSUE TITLE
Allow track field to be locked

### ISSUE THREAD

**Issue by lyramsr** [elamperti/OpenWebScrobbler#52]
this may not seem useful at first, but it would be a help when correcting a big batch of past scrobbles

**Comment by elamperti** [comment]
I'll see if we can fit something like this in a «scrobble fix» option, as there have been several suggestions for that specific activity and I'd rather keep the form simple (easy to understand). So even if this is a simple change, I won't add it right away!

**Comment by elamperti** [comment]
Since my last comment, I implemented d3412da0d9ff777b637f157240bd916d46227ce3 to allow users to edit/clone previous scrobbles. That should be a bit more helpful!

For the moment I won't add a lock to the track field, as it would add unnecessary complexity to the UI, and I want to keep it easy to use/understand for casual users. I'm open to discuss alternative ideas! Thank you :slightly_smiling_face:
