### ISSUE TITLE
Scrobble from Discogs.

### ISSUE THREAD

**Issue by jaccarmac** [elamperti/OpenWebScrobbler#94]
Semi-related to #13.

Discogs has better data for a lot of vinyl releases than Last.fm. There exists a project which scrobbles from Discogs (vinylscrobbler.com), but it has some issues with certain albums (multiple artists, subtracks) and doesn't updated its tracklists as Discogs data changes. I would be interested in an OWS tab to scrobble with data directly from Discogs.

I'm also willing to take point on implementation once my dev environment's up to speed.

**Comment by elamperti** [comment]
Adding Discogs as an alternative would be very useful. I didn't get to this yet, so if you are interested in implementing it feel free to pick it. Thanks for your interest!

Instead of having a different tab or page for it, I'd show two options below the search box to pick which service to use (last.fm/Discogs) and use that as reference througout the rest of the flow.

From a code perspective the store should be in good shape to handle it, though we may need to refactor the transformers to unify the structure of the data from both services.

Please let me know if you want to take this feature so I can assign it to you.

**Comment by jaccarmac** [comment]
Sounds good, and I'll take the assignment!

One thing I notice with the existing flow that would be nice to change for Discogs is the duration selection: Sometimes Discogs releases don't contain durations or they have the wrong ones (for that matter there are also incorrect track orders/names).

But I'll deal with editable bits after I've figured out the API.

**Comment by elamperti** [comment]
Great! All yours :slightly_smiling_face: 

There was a suggestion over at Discord to make albums editable, so we can edit not only duration but also other properties of the tracklist. I'll add an issue for it, as I see there isn't one, then we can tackle that separately, probably after this is working.

**Comment by elamperti** [comment]
Hi @jaccarmac,let me know if you got stuck or need any help with this! Thank you :slightly_smiling_face:

**Comment by jaccarmac** [comment]
No blockers other than my apathy :)

**Comment by elamperti** [comment]
This has been implemented in 4d70a4a :tada:
